package com.sa.branchlocatormap.domain

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room database entity representing a bank branch.
 *
 * This class defines the structure of the `bank_branch_detail` table
 * used by Room for local persistence.
 *
 * It also doubles as your domain model in the current architecture,
 * meaning it is used across:
 * - Data layer (Room)
 * - Repository layer
 * - UI layer
 */
@Entity(tableName = "bank_branch_detail")
data class BankBranchDetail(

    /**
     * Branch display name.
     */
    val name: String = "",

    /**
     * Physical address of the branch.
     */
    val address: String = "",

    /**
     * Precomputed distance string (not dynamically calculated).
     *
     */
    val distance: String = "",

    /**
     * Indicates whether the branch is currently open.
     *
     */
    val isOpen: Boolean = true,

    /**
     * Opening time of the branch (string format).
     */
    val openTime: String = "",

    /**
     * Closing time of the branch (string format).
     */
    val closeTime: String = "",

    /**
     * Indicates whether the user marked this branch as favourite.
     *
     * This mixes UI/user state with branch data. In scalable designs,
     */
    val isFavourite: Boolean = false,

    /**
     * Contact phone number for the branch.
     */
    val phone: String = "",

    /**
     * List of services offered at this branch (e.g. ATM, Loans).
     *
     * Room does NOT support List<String> natively.
     * You must use a TypeConverter for this field.
     */
    val services: List<String> = listOf(),

    /**
     * Geographic latitude coordinate of the branch.
     */
    val latitude: Double = 0.0,

    /**
     * Geographic longitude coordinate of the branch.
     */
    val longitude: Double = 0.0,

    /**
     * Primary key for the Room table.
     *
     * Behavior:
     * - Auto-generated by Room
     * - Uniquely identifies each branch record
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0
)